#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - insit (Based on the older, Installit)
# Started On        - Wed 13 Dec 01:13:55 GMT 2017
# Last Change       - Sun 17 Dec 00:45:10 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This installer is to replace the current installit. The aim of this installer is
# to do away with the need to have several installers, but instead combining them
# all into one easy-to-use installer, while making it more practical to update.
#
# WARNING: Do NOT use this installer until you see this warning line removed.
#          This is only temporary. Eventually the old one will be removed, if all
#          goes well with this "redo".
#
# Although this installer will hopefully replace the current installer, this one
# will still use the same old command line arguments, where possible.
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/wget /bin/{rm,chmod,chown,mkdir}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            INSIT (17th December 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Installer for many shell programs from terminalforlife.

		SYNTAX:     insit [OPTS] WHAT1 WHAT2 WHAT3 . . .
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug                 - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --update|-U             - Replace and update existing files.
		            --uninstall|-u          - Uninstall files installed here.
		            --available|-A          - Output all available programs.

		NOTE:       Where WHAT is the program(s) to install.

		WARNING:    Uninstalling with this program will permanently delete the files it
		            initially installed, but only if you don't have: /usr/bin/gvfs-trash

		            To check for this command, execute the following:

		              which /usr/bin/gvfs-trash
		
		SITE:       https://github.com/terminalforlife
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--update|-U)
			UPDATE="true" ;;
		--uninstall|-u)
			UNINSTALL="true" ;;
		--available|-A)
			AVAIL_SHOW="true" ;;
		-*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac

	shift
done

[ $UID -eq 0 ] || XERR "$LINENO" "Root access is required."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

URL="https://raw.githubusercontent.com/terminalforlife"
BRANCH="master"
PROJECT=""

FILE(){
	# FILE project_name "source_file.sh" "/usr/bin/target_file" 755
	if [ "$UNINSTALL" == "true" ]; then
		/bin/rm "$3"
	else
		/usr/bin/wget -q "$URL/$1/$BRANCH/$2" -O "$3"
		/bin/chown root:root "$3"
		/bin/chmod "$4" "$3"
	fi
}

AVAIL=()

if ! [ "$AVAIL_SHOW" == "true" ]; then
	while [ "$1" ]; do
		case "$1" in
			medlog)
				AVAIL+=("medlog")
				FILE miscellaneous medlog /usr/bin/medlog 755 ;;
			mif)
				AVAIL+=("mif")
				FILE miscellaneous mif /usr/bin/mif 755 ;;
			seewttr)
				AVAIL+=("seewttr")
				FILE miscellaneous seewttr /usr/bin/seewttr 755 ;;
			backmeup)
				AVAIL+=("backmeup")
				FILE miscellaneous backmeup /usr/bin/backmeup 755 ;;
			clean-locales)
				AVAIL+=("clean-locales")
				FILE miscellaneous clean-locales /usr/bin/clean-locales 755 ;;
			mkpass)
				AVAIL+=("mkpass")
				FILE miscellaneous mkpass /usr/bin/mkpass 755 ;;
			mplay)
				AVAIL+=("mplay")
				FILE miscellaneous mplay /usr/bin/mplay 755 ;;
			pagewatch)
				AVAIL+=("pagewatch")
				FILE miscellaneous pagewatch /usr/bin/pagewatch 755 ;;
			redshifter)
				AVAIL+=("redshifter")
				FILE miscellaneous redshifter /usr/bin/redshifter 755 ;;
			tozero)
				AVAIL+=("tozero")
				FILE miscellaneous tozero /usr/bin/tozero 755 ;;
			*)
				ERR "$LINENO" "Unavailable WHAT at: $1" ;;
		esac
	
		shift
	done
else
	printf "%s\n" "${AVAIL[@]}"
fi
