#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - installit (blkid-lite)
# Started On        - Thu 14 Sep 14:44:27 BST 2017
# Last Change       - Thu 14 Sep 15:54:39 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
ERR(){ echo "ERROR: $1" 1>&2; }

DEPCOUNT=0
for DEP in /usr/bin/wget /bin/{chmod,chown,cat,mkdir}
{
	if ! type -P "$DEP" &> /dev/null
	then
		ERR "Dependency '$DEP' not met."
		let DEPCOUNT++
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

shopt -s extglob

USAGE()
{
	/bin/cat <<-EOF
		            INSTALLIT (14th September 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Installer for many shell programs from terminalforlife.

		SYNTAX:     installit [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug                 - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --verbose               - Be verbose about what's going on.
		            --force|-F              - Force installation, despite conflicts.
		            --uninstall|-u          - Uninstall files installed here.
		
		SITE:       https://github.com/terminalforlife
	EOF
}

for ARG in $@
{
	case "$ARG"
	in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--verbose)
			VERBOSE="true" ;;
		--force|-F)
			FORCE_INSTALL="true" ;;
		--uninstall|-u)
			UNINSTALL="true" ;;
		*)
			XERR "Incorrect argument(s) specified." ;;
	esac
}

BEVERBOSE()
{
	if [ "$VERBOSE" == "true" ]
	then
		printf "L%-0.3d: %s\n" "$1" "$2"
	fi
}

[ $UID -eq 0 ] || XERR "Root access is required for installation."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

GITHUB_URL="https://github.com/terminalforlife"
PROJECT="blkid-lite"

if [ "$UNINSTALL" == "true" ]
then
	BEVERBOSE "$LINENO" "Uninstalling program."
fi

for FILENAME in\
\
	"/usr/bin/$PROJECT":"755"
{
	if ! [ "$UNINSTALL" == "true" ]
	then
		BEVERBOSE "$LINENO" "Checking conflict: ${FILENAME%:*}"
		if [ -f "${FILENAME%:*}" ]
		then
			ERR "Conflict found: ${FILENAME%:*}"
			if ! [ "$FORCE_INSTALL" == "true" ]
			then
				continue
			else
				BEVERBOSE "$LINENO" "Item forced: ${FILENAME%:*}"
			fi
		fi

		BEVERBOSE "$LINENO" "Downloading here: ${FILENAME%:*}"
		/usr/bin/wget -cq "$GITHUB_URL/$PROJECT"/blob/master/$PROJECT\
			-O "${FILENAME%:*}"

		BEVERBOSE "$LINENO" "Correcting attributes: ${FILENAME%:*}"
		/bin/chown root:root "${FILENAME%:*}"
		/bin/chmod ${FILENAME/*:} "${FILENAME%:*}"
	else
		if type -P /usr/bin/gvfs-trash &> /dev/null
		then
			BEVERBOSE "$LINENO" "Sending to trash: ${FILENAME%:*}"
			if ! /usr/bin/gvfs-trash "${FILENAME%:*}" &> /dev/null
			then
				ERR "Failed to trash: ${FILENAME%:*}"
			fi
		else
			BEVERBOSE "$LINENO" "Deleting: ${FILENAME%:*}"
			if /bin/rm "${FILENAME%:*}" &> /dev/null
			then
				ERR "Failed to delete: ${FILENAME%:*}"
			fi
		fi
	fi
}

[ "$DEBUGME" == "true" ] && set +xeu
